<?php 

	session_start();
	/*if (isset($_SESSION['UID'] )){
		header("Location: index.php");
    	exit;
	}*/
	$error['pass']='';
	header('Content-Type: text/html; charset=UTF-8');
	//Xử lý đăng nhập
	if (isset($_POST['submit'])) 
	{
    //Lấy dữ liệu nhập vào
    	$username = addslashes($_POST['username']);
    	$password = addslashes($_POST['pass']);
    //Kiểm tra đã nhập đủ tên đăng nhập với mật khẩu chưa
   		 if (!$username || !$password) {
        		$error['pass']= "Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu. <a href='javascript: history.go(-1)'>Trở lại</a>";
    		}
		else{// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php
			$curl = curl_init();
			curl_setopt($curl, CURLOPT_URL, 'https://fathomless-savannah-38522.herokuapp.com/api/auth/login');
			curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($curl, CURLOPT_POST, 1);
			curl_setopt($curl, CURLOPT_POSTFIELDS, "{ \"account\": \"$username\", \"password\": \"$password\"}");
			
			$headers = array();
			$headers[] = 'Accept: */*';
			$headers[] = 'Client-Type: 1';
			$headers[] = 'Content-Type: application/json';
			curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
			
			$resp = curl_exec($curl);
			if (curl_errno($curl)) {
				echo 'Error:' . curl_error($curl);
			}
		$arrResp = json_decode($resp,true);
		//var_dump($weather);
		//print_r($uid);
		if (is_string($arrResp)){
			$_SESSION["UID"]=$arrResp;
			//$message = "aaaaa";
			//$message =$arrResp['message'];;
			//echo "<script type='text/javascript'>alert('$message');
			curl_close($curl);
				echo '<script>';
				echo 'alert("Đăng nhập thành công");';
				echo "window.location = 'index.php';";
				echo '</script>';
			echo $uid;
			echo "</br>";
		}else {
			print_r($arrResp);
			$error['pass']=$arrResp['message'];
			}
		curl_close($curl);
		}
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Đăng nhập</title>

<link href="ver.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<h1 style="color:#FFF">Vui lòng đăng nhập để sử dụng trang web</h1>
	<div style=" width:300px;" id="main">
	<div>Đăng nhập</div>
	<form action="login.php" method="post" name="login" id="form" required />
		<div>Sđt hoặc email </div>
    	<input type="text" name="username" placeholder="sđt hoặc email"required />
    	<div>Mật khẩu</div>
    	<input type="password" name="pass"  />
        <br/>
         <div id="err"><?php echo $error['pass']; ?></div>
        <input type="submit"  name="submit"  value="Đăng nhập"  />
       
	</form>
	<div>Nếu bạn chưa có tài khoản? </div><div><a href="reg.php">Nhấn vào đây để tạo tài khoản</a></div>
    </div>
</body>
</html>
